### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'e.repo.owner')

### ISSUE THREAD

**Issue by stevepeak** [asyncy/hub#28]
https://sentry.io/asyncy/hub/issues/668531366/

```
TypeError: undefined is not an object (evaluating 'e.repo.owner')
  at render (./src/js/views/Index.vue?7191:1:2398)
  at call (./src/js/views/Index.vue?7191:1:2237)
  at apply (./src/js/main.js:81:7)
  at call (./src/js/main.js:79:7)
...
(32 additional frame(s) were not displayed)
```

**Comment by JeanBarriere** [comment]
Yep I saw it, I already fixed it but I didn't made the PR yet
